modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/ZigyTheBird/PlayerAnimationLibrary/issues"
license = "MIT License"

[[mods]]
modId = "player_animation_library"
version = "${version}"
displayName = "Player Animation Library"
authors = "Zigy, dima_dencep"
description = '''
A library that allows mods to animate the player, in a way that doesn't conflict with other mods. (and much more!)
'''

displayURL = "https://docs.zigythebird.com/pal/intro"
logoFile = "icon.png"

[[dependencies.player_animation_library]]
modId = "neoforge"
type = "required"
versionRange = "[21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.player_animation_library]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "player_animation_library.mixins.json"
