modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "player_animation_library"
version = "${version}"
displayName = "Player Animation Library"
authors = "Zigy"
description = '''
Library that allows mods and data packs to animate the player.
'''
logoFile = "assets/player_animation_library/icon.png"

[[dependencies.player_animation_library]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.player_animation_library]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "player_animation_library.mixins.json"
