/*
 * MIT License
 *
 * Copyright (c) 2022 KosmX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.zigythebird.playeranim.animation.layered.modifier;

import com.zigythebird.playeranim.animation.AnimationData;
import com.zigythebird.playeranim.animation.EasingType;
import com.zigythebird.playeranim.animation.layered.IAnimation;
import com.zigythebird.playeranim.cache.PlayerAnimBone;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Use with ModifierLayer.
 * Set an animation as a fade from.
 * length in ticks
 */
public abstract class AbstractFadeModifier extends AbstractModifier {

    protected int time = 0;
    protected int length;
    protected float tickDelta;

    /**
     * Animation to move from, null if transparent (easing in)
     * use setBeginAnimation(IAnimation); //generated by Lombok plugin
     */
    @Nullable
    @Setter
    protected IAnimation beginAnimation;

    protected AbstractFadeModifier(int length) {
        this.length = length;
    }

    @Override
    public boolean isActive() {
        return super.isActive() || beginAnimation != null && beginAnimation.isActive();
    }

    @Override
    public boolean canRemove() {
        return this.length <= time;
    }

    @Override
    public void setupAnim(AnimationData state) {
        super.setupAnim(state);
        if (beginAnimation != null) beginAnimation.setupAnim(state);
        tickDelta = state.getPartialTick();
    }

    @Override
    public void tick(AnimationData state) {
        super.tick(state);
        if (beginAnimation != null) beginAnimation.tick(state);
        this.time++;
    }

    @Override
    public void get3DTransform(@NotNull PlayerAnimBone bone) {
        super.get3DTransform(bone);
        if (calculateProgress(tickDelta) > 1) return;
        //Todo: Maybe look into optimizing this to work better with the new system
        PlayerAnimBone animatedBone = new PlayerAnimBone(bone.getName());
        animatedBone.copyOtherBone(bone);
        float a = getAlpha(bone, calculateProgress(tickDelta));
        if (beginAnimation != null && beginAnimation.isActive()) beginAnimation.get3DTransform(bone);
        bone.scale(a).add(bone.scale(1 - a));
    }

    protected float calculateProgress(float f) {
        float actualTime = time + f;
        return actualTime / length;
    }

    /**
     * Get the alpha at the given progress
     * @param bone current bone
     * @param progress  animation progress, float between 0 and 1
     * @return alpha, float between 0 and 1, lower value means less visible from animation
     */
    protected abstract float getAlpha(PlayerAnimBone bone, float progress);

    /**
     * Creates a standard fade with some easing in it.
     * @param length ease length in ticks
     * @param ease   ease function from {@link EasingType}
     * @return fade modifier
     */
    public static AbstractFadeModifier standardFadeIn(int length, EasingType ease) {
        return new AbstractFadeModifier(length) {
            @Override
            protected float getAlpha(PlayerAnimBone bone, float progress) {
                return ease.buildTransformer(null).apply((double) progress).floatValue();
            }
        };
    }

    /**
     * Functional constructor for functional folks
     * @param length   ease length
     * @param function ease function
     * @return fade
     */
    public static AbstractFadeModifier functionalFadeIn(int length, EasingFunction function) {
        return new AbstractFadeModifier(length) {
            @Override
            protected float getAlpha(PlayerAnimBone bone, float progress) {
                return function.ease(bone, progress);
            }
        };
    }

    @FunctionalInterface
    public interface EasingFunction {
        float ease(PlayerAnimBone bone, float value);
    }
}
